version: '3.6'
services:
  postgres:
    image: postgres:11
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    restart: always
    volumes:
    - db_veronica:/var/lib/postgresql/data
    - ./postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
  veronica:
    build:
      context: .
    depends_on:
      - postgres
    ports:
    - "8080:8080"
volumes:
  db_veronica:
